name: ClickTheHelp
version: 0.0.1
main: cc.mcii.ClickTheHelp.ClickTheHelp
api-version: '1.16'

commands:
  help:
    description: "替换原版/help列表"
    usage: "用法：/help"
  clickthehelp:
    description: "插件命令"
    usage: "用法：/clickthehelp reload"
    permission: clickthehelp.config

permissions:
  clickthehelp.config:
    description: 配置插件的权限
    default: op