name: ClickTheHelp
version: 0.0.2
main: cc.mcii.ClickTheHelp.ClickTheHelp
api-version: '1.13'

commands:
  help:
    description: "Replaces vanilla /help pages"
    usage: "Usage: /help [helpname]"
  clickthehelp:
    description: "Config of ClickTheHelp"
    usage: "Usage: /clickthehelp {reload}"
    permission: clickthehelp.config

permissions:
  clickthehelp.config:
    description: Config of ClickTheHelp
    default: op